#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v20
# autospec commit: f35655a
#
Name     : pypi-doit
Version  : 0.36.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/5a/36/66b7dea1bb5688ba0d2d7bc113e9c0d57df697bd3f39ce2a139d9612aeee/doit-0.36.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/5a/36/66b7dea1bb5688ba0d2d7bc113e9c0d57df697bd3f39ce2a139d9612aeee/doit-0.36.0.tar.gz
Summary  : doit - Automation Tool
Group    : Development/Tools
License  : MIT
Requires: pypi-doit-bin = %{version}-%{release}
Requires: pypi-doit-license = %{version}-%{release}
Requires: pypi-doit-python = %{version}-%{release}
Requires: pypi-doit-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
*doit* comes from the idea of bringing the power of build-tools to execute any
        kind of task
        
        *doit* can be uses as a simple **Task Runner** allowing you to easily define ad hoc
        tasks, helping you to organize all your project related tasks in an unified
        easy-to-use & discoverable way.
        
        *doit* scales-up with an efficient execution model like a **build-tool**.
        *doit* creates a DAG (direct acyclic graph) and is able to cache task results.
        It ensures that only required tasks will be executed and in the correct order
        (aka incremental-builds).
        
        The *up-to-date* check to cache task results is not restricted to looking for
        file modification on dependencies.  Nor it requires "target" files.
        So it is also suitable to handle **workflows** not handled by traditional build-tools.
        
        Tasks' dependencies and creation can be done dynamically during it is execution
        making it suitable to drive complex workflows and **pipelines**.
        
        *doit* is build with a plugin architecture allowing extensible commands, custom
        output, storage backend and "task loader". It also provides an API allowing
        users to create new applications/tools leveraging *doit* functionality like a framework.
        
        *doit* is a mature project being actively developed for more than 10 years.

%package bin
Summary: bin components for the pypi-doit package.
Group: Binaries
Requires: pypi-doit-license = %{version}-%{release}

%description bin
bin components for the pypi-doit package.


%package license
Summary: license components for the pypi-doit package.
Group: Default

%description license
license components for the pypi-doit package.


%package python
Summary: python components for the pypi-doit package.
Group: Default
Requires: pypi-doit-python3 = %{version}-%{release}

%description python
python components for the pypi-doit package.


%package python3
Summary: python3 components for the pypi-doit package.
Group: Default
Requires: python3-core
Provides: pypi(doit)
Requires: pypi(cloudpickle)
Requires: pypi(importlib_metadata)

%description python3
python3 components for the pypi-doit package.


%prep
%setup -q -n doit-0.36.0
cd %{_builddir}/doit-0.36.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1730207758
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-doit
cp %{_builddir}/doit-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-doit/36c09311929597146eeb59023540dc40bafb9fef || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doit

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-doit/36c09311929597146eeb59023540dc40bafb9fef

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
